"""Add followers

Revision ID: 6f582146c171
Revises: 95dbe58da754
Create Date: 2020-07-09 22:40:06.309009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f582146c171'
down_revision = '95dbe58da754'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followings',
    sa.Column('followings_id', sa.Integer(), nullable=False),
    sa.Column('follower', sa.Integer(), nullable=True),
    sa.Column('follows', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['follower'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['follows'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('followings_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followings')
    # ### end Alembic commands ###
